server:
  port: 45000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:31000/test
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
    show-sql: true
    database: mysql
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect
#spring:
#  profiles:
#    active: local
#  batch:
#    job:
#      names: ${job.name:NONE} #NONE은 임의의 문자를 의미, 수행 할 Job Parameter가 들어오지 않으면 아무것도 시작되지 않음
#      enabled: false
##    jdbc:
##      initializer-schema: always
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    show-sql: false
#    properties:
#      hibernate:
#        allow_update_outside_transaction: true
#        default_batch_fetch_size: 1000
#        format_sql: true
#        temp:
#          use_jdbc_metadata_defaults: false #postgresql: PgConnection.createClob is not yet implemented 에러 방지
#      #        jdbc:
#      #          batch_size: 10
#---
#spring:
#  config:
#    activate:
#      on_profile: local
#  datasource:
#    mysql:
#      jdbc-url: jdbc:mysql://localhost:31000/test
#      username: root
#      password: root
#      driver-class-name: com.mysql.cj.jdbc.Driver
#    oracle:
#      jdbc-url: jdbc:oracle:thin:@//localhost:30000/XE
#      username: scott
#      password: tiger
#      driver-class-name: oracle.jdbc.OracleDriver
#---
#spring:
#  config:
#    activate:
#      on_profile: dev
#  datasource:
#    mysql:
#      jdbc-url: jdbc:mysql://mysql/test
#      username: root
#      password: root
#      driver-class-name: com.mysql.cj.jdbc.Driver
#    oracle:
#      jdbc-url: jdbc:oracle:thin:@//oracle/XE
#      username: scott
#      password: tiger
#      driver-class-name: oracle.jdbc.OracleDriver
#
##spring:
##  profiles:
##    active: local
##  jpa:
##    #    database: mysql
##    #    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
##    hibernate:
##      ddl-auto: create-drop
##    show-sql: true
##    properties:
##      hibernate:
##        #        jdbc:
##        #          lob:
##        #            non_contextual_creation: true
##        dialect: org.hibernate.spatial.dialect.mysql.MySQL56InnoDBSpatialDialect
##        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
##---
##spring:
##  config:
##    activate:
##      on_profile: local
##  datasource:
##    mysql:
##      driver-class-name: com.mysql.cj.jdbc.Driver
##      jdbc-url: jdbc:mysql://localhost:31000/test
##      username: root
##      password: root
